image:
  file: .gitpod.Dockerfile

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - before: |
      (
        printf '\e[3J\033c\e[3J';

        if test -n "${CUSTOM_GH_TOKEN:-}"; then {
          for i in {1..5}; do
            printf '%s\n' "$CUSTOM_GH_TOKEN" | gh auth login --with-token && {
              printf 'info: %s\n' 'Successfully logged into "gh" CLI';
              break;
            }
          done
        } else {
          printf 'error: %s\n' 'CUSTOM_GH_TOKEN was not defined at https://gitpod.io/variables with "*/*" as scope';
          exit;
        } fi

        git config --global --add credential.helper "!/usr/bin/env gh auth git-credential" && \
          printf 'info: %s\n' '"gh" CLI was setup as a git-credential-helper';
        
        if test -n "${CUSTOM_REPO_URLS:-}"; then {
          IFS='~' read -ra urls <<<"$CUSTOM_REPO_URLS";
          for repo in "${urls[@]}"; do {
            IFS='|' read -r host owner reponame <<<"$repo"
            if test ! -e "$GITPOD_REPO_ROOT/$reponame"; then {
              git -C "$GITPOD_REPO_ROOT" clone --filter=tree:0 "https://${host}/${owner}/${reponame}";
            } fi
          } done
        } else {
          printf 'error: %s\n' 'CUSTOM_REPO_URLS was not passed as a parameter in your Gitpod URL';
          exit;
        } fi
      )
